#!/bin/bash
for i in `seq 1 22`;
do
  echo "param SolveSlot :="$i";" > SolveSlot.dat
  glpsol --check --math BessyRooms.mod -d SolveSlot.dat -d courses.dat -d default.dat  -d RoomData.dat -d SplitForPhase.dat -d RequiredBuildings.dat -d PriorityBuildings.dat --wlp TEST.lp
  gurobi_cl Threads=8 TimeLimit=1000 ResultFile=test.sol TEST.lp
  cat test.sol | grep 'h(' | grep -v ') 0' > rusl.txt
  sed -i 's/,/ /g' rusl.txt
  sed -i 's/h(/ /g' rusl.txt
  sed -i 's/)/ /g' rusl.txt
  echo "param hfix := " >  hfix.dat
  cat rusl.txt >> hfix.dat
  echo ";" >> hfix.dat
  echo "end;" >> hfix.dat
  glpsol --math BessyRooms.mod -d SolveSlot.dat -d courses.dat -d default.dat -d RoomData.dat -d SplitForPhase.dat -d RequiredBuildings.dat -d hfix.dat
  mv lausn.csv lausn$i.csv
  git add lausn$i.csv
  git commit lausn$i.csv -m "lausn"
  git push
done
